### ISSUE TITLE
When will appimages for chirp be available again?

### ISSUE THREAD

**Issue by g-billingsley** [goldstar611/chirp-appimage#2]
Prefer to use appimages instead of installing chirp-next for Linux Mint. I have never had a successful install from source tarball or python wheel.

**Comment by goldstar611** [comment]
Hey, sorry about the mess here. I'm working on getting the build and release job going again and will do some testing on a few distributions today.

**Comment by goldstar611** [comment]
Check out https://github.com/goldstar611/chirp-appimage/releases/tag/20230411 and let me know if you encounter any errors. I ran the x86_64 AppImage and it looked like dark mode was enabled for some reason. I'm not even sure if CHIRP has a dark mode so it may be something wrong in the AppImage recipe.

**Comment by goldstar611** [comment]
I know it's not portable, but if you did want to install CHIRP-next from source on Linux Mint 21.1, I used the following terminal commands and was up in less than 5 minutes.

```bash
# Get dependencies
sudo apt install python3-pip python3-wxgtk4.0

# Install CHIRP from source
# Optionally prepend sudo to install as root and put chirp in the system path
version=20230411
pip install https://trac.chirp.danplanet.com/chirp_next/next-${version}/chirp-${version}.tar.gz

# I ran pip as non-root so it installed the chirp shortcut somewhere in my home directory
find ~ -type f -name chirp

# There it is, run it.
/home/user/.local/bin/chirp

# On first run, CHIRP will ask if you want to create a menu shortcut.
```

**Comment by g-billingsley** [comment]
I tried the new appimage 20230411 and it seems to work just fine. It's not in dark mode, and appears to follow whatever theme the desktop manager is currently using.

I'll give a "regular" install another try at some point in the future. But for the time being I like the ease and flexibility that appimages give me. I keep an archive of past images because I've have some instances where a new release had problems programming an older radio, and going back a few revisions worked.

Thanks a bunch for building this release!

**Comment by goldstar611** [comment]
Awesome! Thanks for taking verifying that it works correctly. When I tested on PopOS it had the dark mode so maybe it's something specific to pop. 

> I keep an archive of past images

If you would be so kind to upload one of those older AppImages here so I could see if the same issue was present in the older builds, that would be amazing!

**Comment by g-billingsley** [comment]
GitHub isn't allowing me to up load a file bigger than 25MB.

**Comment by goldstar611** [comment]
And it's already compressed so putting it inside a zip file won't help much. Ok, no worries I appreciate your help and feedback!
