### ISSUE TITLE
error on Pi 4

### ISSUE THREAD

**Issue by km4ack** [goldstar611/chirp-appimage#4]
With the latest image, I get an error when starting. Pi 4 4GB Pi OS 32bit

```
(process:9749): Gtk-WARNING **: 09:39:00.560: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/tmp/.mount_chirpHkxkSl/usr/bin/chirpw", line 135, in <module>
    a = mainapp.ChirpMain()
  File "/tmp/.mount_chirpHkxkSl/usr/lib/python2.7/site-packages/chirp/ui/mainapp.py", line 2289, in __init__
    self._set_icon()  # Windows gets the icon from the exe
  File "/tmp/.mount_chirpHkxkSl/usr/lib/python2.7/site-packages/chirp/ui/mainapp.py", line 2182, in _set_icon
    self.set_icon_from_file(path)
glib.GError: Couldn't recognize the image file format for file '/tmp/.mount_chirpHkxkSl/usr/share/pixmaps/chirp.png'
```

**Comment by goldstar611** [comment]
Hey Jason,

Thanks for the report. I'll take a look and see what changed.

**Comment by goldstar611** [comment]
The problem is in `$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache` where the png, jpeg, and pnm format support was removed.

I need to figure out who to send a bug report to *OR* copy the CHIRP svg into the pixmaps directory. I'll at least try to track down the change.

```diff
user@host:~/Downloads$ diff -u '/home/user/Downloads/Chirp-daily-20221122-x86_64/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache' /home/user/Downloads/Chirp-daily-20221123-x86_64/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
--- /home/user/Downloads/Chirp-daily-20221122-x86_64/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache	2022-11-23 12:26:28.799806946 -0600
+++ /home/user/Downloads/Chirp-daily-20221123-x86_64/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache	2022-11-23 12:32:26.382924626 -0600
@@ -1,6 +1,6 @@
 # GdkPixbuf Image Loader Modules file
 # Automatically generated file, do not edit
-# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.40.0
+# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.42.8
 #
 # LoaderDir = /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
 #
@@ -35,18 +35,6 @@
 "  \001   " "zz znz" 100
 "  \002   " "zz znz" 100
 
-"libpixbufloader-jpeg.so"
-"jpeg" 5 "gdk-pixbuf" "JPEG" "LGPL"
-"image/jpeg" ""
-"jpeg" "jpe" "jpg" ""
-"\377\330" "" 100
-
-"libpixbufloader-png.so"
-"png" 5 "gdk-pixbuf" "PNG" "LGPL"
-"image/png" ""
-"png" ""
-"\211PNG\r\n\032\n" "" 100
-
 "libpixbufloader-pnm.so"
 "pnm" 4 "gdk-pixbuf" "PNM/PBM/PGM/PPM" "LGPL"
 "image/x-portable-anymap" "image/x-portable-bitmap" "image/x-portable-graymap" "image/x-portable-pixmap" ""
```

**Comment by calinb7** [comment]
_The problem is in $APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache where the png and jpeg format support was removed._

So presumably it was removed from the aarch64 library too?

Thanks so much for your work, Tony!

**Comment by goldstar611** [comment]
It's strange because the affected file is auto-generated and it has a hint of the package version `gdk-pixbuf-2.42.8` that generated the file. BUT version 2.42.8 is not in the xenial (18.04) or bionic (20.04) repositories used to create the AppImage. That version is in jammy (22.04) however which is used by the container (a la "ubuntu-latest"). I guess what I'm saying is that it could even be a Ubuntu 22.04 change. I'll put in a work around and continue digging after the holidays :)

**Comment by goldstar611** [comment]
Hey @km4ack and @calinb7,

Sorry for the delay in fixing the AppImage but I finally figured out what the problem and a workaround. 

I'm manually starting a build now that the fix is merged. Since the build is out of sync from Dan's build process, the  filename won't match the CHIRP version in the app.

https://github.com/goldstar611/chirp-appimage/releases

**Comment by calinb7** [comment]
Thanks so much for your efforts, Tony! There's no need to apologize. I recently had a libc6 nightmare while building the pat-gensio (includes AX.25 and a 1200 baud AFSK modem) version of the Winlink program for amd64. I never did get the build scripts and makefiles straightened out but figured out a way to hack the build files to get them to use my libc6 version between a couple of build steps. Strangely, the arm64 binary ran on my Pinebook Pro and Pinephone right from github!

So I understand how much work goes into these things and, again, I really appreciate it.

I tested your new AppImages for both arm64 (Manjaro on a Pinebook Pro) and amd64 (MX-Linux on an HP laptop). Both worked normally (great)!

Cal AD8Q

**Comment by km4ack** [comment]
Thanks for the update and your continued work on this!
