### ISSUE TITLE
Error on Fedora Silverblue 38

### ISSUE THREAD

**Issue by ma3yta** [goldstar611/chirp-appimage#5]
```
(chirp:5280): GLib-GIO-ERROR **: 09:02:14.089: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
fish: Job 1, './Chirp-next-20230818-x86_64.Ap…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by goldstar611** [comment]
Hi, can you let me know which operating system you were using when you saw this sigtrap error? Thanks 

[Edit] I see `Fedora Silverblue 38` in the title now, I'll take a look!

**Comment by goldstar611** [comment]
Hi @ma3yta Let me know if the latest change fixes your problem on Fedora Silverblue. I tested it out but it's always great to get feedback. Thanks!

**Comment by ma3yta** [comment]
Hi @goldstar611 It works fine. Thank you.
