### ISSUE TITLE
Chirp-daily-20221229-x86_64 fails to launch on PureOS 10

### ISSUE THREAD

**Issue by sysfu** [goldstar611/chirp-appimage#6]
Latest release won't launch, the previous release CHIRP daily-20221217 works.

here's the terminal output:

```
$ ./Chirp-daily-20221229-x86_64_7e675ecc9d00628b38e000a1b8434c89.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/tmp/.mount_Chirp-6zoNlc/usr/bin/chirp", line 33, in <module>
    sys.exit(load_entry_point('chirp===daily-20221229', 'console_scripts', 'chirp')())
  File "/tmp/.mount_Chirp-6zoNlc/usr/lib/python3.10/site-packages/chirp/wxui/__init__.py", line 39, in chirpmain
    import wx
  File "/tmp/.mount_Chirp-6zoNlc/usr/lib/python3/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_Chirp-6zoNlc/usr/lib/python3/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /tmp/.mount_Chirp-6zoNlc/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags
```

**Comment by goldstar611** [comment]
Thanks for the bug report. I can confirm this same error appears on the armhf variant as well so I suppose I've forgotten to include a package somewhere.

I'll get it sorted out soon. This is my first time packaging up a gtk3 app :)

**Comment by goldstar611** [comment]
whoops, pushed straight into the default branch and closed the issue!

**Comment by goldstar611** [comment]
> Seemed like madness manually installing flatpaks from manual website file downloads instead of flatpak repos.

That's my fault actually. There was no good way to run CHIRP on newer systems that lacked python2 packages and I came up with the flatpak idea and handed it to Dan. There never was a plan to put it on FlatHub as it was just a crutch to hold everyone over, myself included. Depending on how much feedback there is on the issue tracker, there may or may not be a flatpak release since someone has to do the work to update *that* recipe.

**Comment by goldstar611** [comment]
Ok I think I worked out a few bugs. Check the latest release to see if the problem is resolved. Thanks!

**Comment by goldstar611** [comment]
Yep the new version thing will show up until I get a fox for that. I'll open another issue for it.
