### ISSUE TITLE
APPRUN_ERROR: No such file or directory     On default install Raspian

### ISSUE THREAD

**Issue by virtual812** [goldstar611/chirp-appimage#7]
I have the 20230106-armhf daily and after setting it as executable i get the message "APPRUN_ERROR: No such file or directory"

Any help appreciated.

**Comment by goldstar611** [comment]
Hi, I'm waiting on https://github.com/AppImageCrafters/appimage-builder/pull/289 to be merged upstream. I'll ping them and see if there's anything I can do.

**Comment by goldstar611** [comment]
And if you need something as a quick fix you can use the last release of chirp daily before it switch to python3 and gtk3. https://github.com/goldstar611/chirp-appimage/releases/tag/20221229

**Comment by goldstar611** [comment]
@virtual812 ,
I have a quick fix released at https://github.com/goldstar611/chirp-appimage/releases/tag/20230118
Let me know if that armhf version is working for you on the raspberry pi.
Thanks!
